# Spring properties
spring:
  application:
    name: authentication-service
  freemarker:
    enabled: false
  thymeleaf:
    enabled: false

error.path: /error

server.port: 2222

eureka:
  client:
    serviceUrl:
      defaultZone: http://${registration.server.hostname}:1111/eureka/
  instance:
    leaseRenewalIntervalInSeconds: 10

management.endpoints.web.exposure.include: '*'
