# Spring properties
spring:
  application:
    name: director-service
  freemarker:
    enabled: false

error.path: /error

server.port: 3333

eureka:
  client:
    serviceUrl:
      defaultZone: http://${registration.server.hostname}:1111/eureka/
  instance:
    leaseRenewalIntervalInSeconds: 10
management.endpoints.web.exposure.include: '*'

