# Spring properties
spring:
  application:
     name: managers-service
  freemarker:
    enabled: false
  thymeleaf:
    cache: false
    prefix: classpath:/managers-server/templates/

error.path: /error

server.port: 3333

eureka:
  client:
    serviceUrl:
      defaultZone: http://${authentication.server.hostname}:1111/eureka/
  instance:
    leaseRenewalIntervalInSeconds: 10
management.endpoints.web.exposure.include: '*'

