# Spring properties
spring:
  application:
    name: profile-service
  freemarker:
    enabled: false

error.path: /error

server.port: 4444

eureka:
  client:
    serviceUrl:
      defaultZone: http://${registration.server.hostname}:1111/eureka/
  instance:
    leaseRenewalIntervalInSeconds: 10

management.endpoints.web.exposure.include: '*'

