# Spring properties
spring:
  application:
    name: university-service
  freemarker:
    enabled: false

error.path: /error

server.port: 5555

eureka:
  client:
    serviceUrl:
      defaultZone: http://${registration.server.hostname}:1111/eureka/
  instance:
    leaseRenewalIntervalInSeconds: 10
management.endpoints.web.exposure.include: '*'
